### ISSUE TITLE
Cache target directory between runs

### ISSUE THREAD

**Issue by sebschmi** [actions-rs/cargo#110]
## Motivation

Building a Rust project takes a lot of time if many dependencies are involved. In my case I have >2 minutes build time, of which only a few seconds are from my own crates. This could be greatly reduced by caching the target directory with [the dependency cache](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows).

## Workflow example

```yaml
steps:
  - name: Cargo check
    uses: actions-rs/cargo@v2
    with:
      command: check
      use-cache: true # 
```

## Additional context

The action is [actions/cache](https://github.com/actions/cache).

There is an example on how to use it for the [.cargo directory](https://github.com/actions/cache/blob/main/examples.md#rust---cargo). Employing that example prevents cargo from redownloading all the crates on every run, but it still recompiles them.
