### ISSUE TITLE
Cross builds on macOS runners cannot find Cargo.toml?

### ISSUE THREAD

**Issue by brainstorm** [actions-rs/cargo#113]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

Ubuntu builds succeed, but the same step definition for [`runs-on: macOS-latest` is unable to find `cargo`?](https://github.com/rust-bio/rust-htslib/pull/275/checks?check_run_id=1164087327):

```
Run actions-rs/cargo@v1.0.1
Install cross
cross build --target x86_64-unknown-linux-musl --all-features --verbose
+ "cargo" "build" "--target" "x86_64-unknown-linux-musl" "--all-features" "--verbose"
error: could not find `Cargo.toml` in `/Users/runner/work/rust-htslib/rust-htslib` or any parent directory
Error: The process 'cross' failed with exit code 101
```

## Workflow code

```yaml

  Testing-OSX:
    needs: Formatting
    runs-on: macOS-latest
    steps:
      - name: Test musl build with all features and debug symbols (non --release) on OSX
        uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl --all-features --verbose
```
