### ISSUE TITLE
error: could not create home directory: '/.rustup' with use-cross

### ISSUE THREAD

**Issue by lpil** [actions-rs/cargo#183]
Hello! Thank you for this useful project

## Description

A couple days ago my workflow stopped working without modification. Upon attempting to run `cargo build` with `use-cross` set to true I get this error:
```
Status: Downloaded newer image for clux/muslrust:latest
error: could not create home directory: '/.rustup'
Error: error: caused by: Permission denied (os error 13)
Error: The process 'cross' failed with exit code 1
```

## Workflow code

Here is my workflow: https://github.com/gleam-lang/gleam/blob/e25991fe92901577b47b0c6d3d71894a7abbc5e0/.github/workflows/ci.yaml#L46-L51

I believe this to be a reproduction:
```yaml
name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    env:
      RUSTFLAGS: "-D warnings"
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        profile: minimal
        override: true

    - name: Build binary
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-musl
```
 

## Action output

Here is the full log https://github.com/gleam-lang/gleam/runs/2828986249?check_suite_focus=true

## Expected behavior

`cargo build` runs

Thanks,
Louis
