### ISSUE TITLE
echo workflow commands for each cargo error and warning

### ISSUE THREAD

**Issue by hhirtz** [actions-rs/cargo#194]
Do the checklist before filing an issue:

 * [ ] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

nice-to-have feature request: instead of having to look through job logs, the cargo action would show warnings and errors from cargo directly in the PR file view.

For example, to show an error in the file view in shell:

    echo "::error file=src/lib.rs,line=30,endLine=30::`#![feature]` may not be used on the stable release channel"

## Workflow example

No change in workflow files, the typical use of this action would Just Work:

```yaml
on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
```

## Additional context

See https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions

I'm not willing to work on this at the moment and just wanted to hear your thoughts about this feature.
