### ISSUE TITLE
`args` does not evaluate file globs

### ISSUE THREAD

**Issue by JonasCir** [actions-rs/cargo#200]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

First, thanks for creating these actions, super helpful!

In my project, I have a couple of rust files which are there as test resources, however, I want them to be automatically checked by `cargo fmt` as well. Since they are not attached to any project, I need to pass the file paths directly to `rustfmt`. 

`cargo fmt -- tests/resources/**/*.rs --check` works perfectly fine from my shell but it appears that this action does not expand glob patterns, which causes the following action to fail.

## Workflow code

```yaml
      - name: Run cargo fmt on tests resources
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- tests/resources/**/*.rs --check
```
 
## Action output

```
Run actions-rs/cargo@v1
/home/runner/.cargo/bin/cargo fmt -- tests/resources/**/*.rs --check
Error: file `tests/resources/**/*.rs` does not exist
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

## Expected behavior

Glob patterns are expanded and the action checks all files.

## Additional context

I found a way around it:
```
      - name: Gather test resources
        run: echo "TEST_RESOURCES_RUST=$(ls tests/resources/**/*.rs | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run cargo fmt on tests resources
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- ${{ env.TEST_RESOURCES_RUST }} --check
```
