### ISSUE TITLE
Warning with rustfmt and cargo-fmt

### ISSUE THREAD

**Issue by giggio** [actions-rs/cargo#209]
## Description

When running, we get a warning for rustfmt and cargo-fmt.

## Workflow code

```yaml
- name: Build amd64
  uses: actions-rs/cargo@v1
  with:
    command: build
    use-cross: true
    args: --release --target x86_64-unknown-linux-musl
```
 
Reference yaml:
https://github.com/giggio/speedtest/blob/4ab093da7cebc6c0e7430bb4aba761e92c81df3b/.github/workflows/image.yml#L40-L45

## Action output

```
warning: tool `rustfmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
Warning: warning: tool `cargo-fmt` is already installed, remove it from `/home/runner/.cargo/bin`, then run `rustup update` to have rustup manage this tool.
```

See the warning on the action:
https://github.com/giggio/speedtest/runs/6816591384?check_suite_focus=true#step:8:13

## Expected behavior

No warnings.

## Additional context

Happens for ARM and amd64, they are both on the build output and yaml.
