### ISSUE TITLE
How do I find the build artefacts?

### ISSUE THREAD

**Issue by eggbean** [actions-rs/cargo#218]
My workflow seems to successfully build but I do not know where the build artefacts are. I tried doing a `find \` but it didn't find anything.

How do I determine the location of the compiled binary and man files?

```
jobs:
  armv7l:
    name: armv7l build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ogham/exa
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
```

**Comment by devdailytester** [comment]
+1,i also want to get the output binary
seems related to https://github.com/actions-rs/cargo/issues/44

**Comment by eggbean** [comment]
Could you tell me if you figure it out? I have had this project on hold for a month now, as I still cannot find it.

**Comment by devdailytester** [comment]
i know where is the build artifact but i dont know how to move to release or do stuff with it.looking at other actions

**Comment by eggbean** [comment]
You know where it is? What is the location? I can't understand why you can't upload it if you know where it is.

**Comment by devdailytester** [comment]
i dont know how to upload i tried use other,release action.
The location is like release\build\
just like common cargo build.you can try build locally and get the full view its the same,

**Comment by eggbean** [comment]
I don't know what you mean by `release\build`. Why is there a backslash? Is that the full path? I cannot find that directory.

If you know where the build artefacts are you can upload them using `actions/upload-artifact@v2`.

**Comment by devdailytester** [comment]
that is of course not the full path lol.
you can try compile in your local machine and see the directory,each platform has its own tweakrs(different output path).
thanks will try out that upload action.

**Comment by cheolgyu** [comment]
https://doc.rust-lang.org/cargo/commands/cargo-build.html#output-options
```
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose --package batch --bin kr_timer  --target-dir ./build
    - name: tar
      run: tar cvf kr_timer.tar.gz ./build/release/kr_timer* ./.env.prod
```
