### ISSUE TITLE
Support changing working directory

### ISSUE THREAD

**Issue by jgrund** [actions-rs/cargo#6]
So cargo commands can be run in subdirectories.

**Comment by svartalf** [comment]
Sounds like a good idea to add, smth like
```yaml
- uses: actions-rs/cargo@v1
  with:
    cwd: ./sub-folder
    command: build
```

I'll try to add it tomorrow

**Comment by jgrund** [comment]
I have a top-level workspace, and then a workspace in a subfolder within the same project. 

The workspaces are not tied together by cargo (one is backend code, one is wasm front-end code), so I can't use `cargo -p` from the top level.

**Comment by svartalf** [comment]
@jgrund I researched it for a bit and found the [`working-directory`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) parameter for `steps`, that should do the job for your case.

**Comment by Arnavion** [comment]
`working-directory` appears to only work for the `run` action (which your docs link is for), not for arbitrary actions like `actions-rs/cargo`

**Comment by nelsonjchen** [comment]
Here's an example of `working-directory` not working for non-`run` actions:

https://github.com/nelsonjchen/com-rs/commit/c3af52907da12cb4331c17a48e84f4a6a52afa0c/checks?check_suite_id=366094450

Could this issue be reopened?

**Comment by Arnavion** [comment]
@nelsonjchen You should be able to do `command: build --manifest-path examples/aggregation/Cargo.toml` instead of needing to change the working directory.

**Comment by nelsonjchen** [comment]
@Arnavion I had to use `args:` (only `build` is accepted in `command:`)  but otherwise yeah, that works for me.

https://github.com/nelsonjchen/com-rs/commit/0b6f0417c41e1a90084161b7cd68fac1ebc8395b

Thanks!

**Comment by dbrgn** [comment]
I also ran into this issue. A proper `working-directory` argument would be nice, even though the workaround seems to work.

**Comment by Xcodo** [comment]
This tripped me up a bit today too. `working_directory` would be clearer than using `--manifest-path` for me.

**Comment by bfrog** [comment]
I ran into this today myself while working on using actions for CI on a complex workspace.

I would much prefer working_directory here.

**Comment by mtslzr** [comment]
Chiming in with another +1. While the work-around works... the purpose of using a package it to have the workflow be more elegant. Adding support for `working-directory` is definitely preferred.

**Comment by MarcoPolo** [comment]
The workaround doesn't seem to work with `cross`. 

Specifically I'm doing:
```
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-musl --manifest-path hello-lambda/Cargo.toml
```

And it fails in an error about musl-gcc.

**Comment by MarcoPolo** [comment]
As a workaround you can use my fork like so:
```
...
      - uses: marcopolo/cargo@master
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-musl
          working-directory: hello-lambda
```

I added a PR here: https://github.com/actions-rs/cargo/pull/59
