### ISSUE TITLE
What does this get me?

### ISSUE THREAD

**Issue by dtolnay** [actions-rs/cargo#72]
This is my first time trying GitHub Actions, so apologies for the basic question.

I see that the [example workflow in this repo's readme](https://github.com/actions-rs/cargo/tree/6c501d70ccddd05d7d3cda545dc6099619d5e0ee#example-workflow) contains this example step:

```yml
- uses: actions-rs/cargo@v1
  with:
    command: build
    args: --release --all-features
```

Based on the readme of this repo it wasn't clear to me what benefit this would have over just:

```yml
- run: cargo build --release --all-features
```

which [appears to work](https://github.com/alexcrichton/toml-rs/blob/7a43ac9e9c28afec8414f6d924024f5d33fe8fa2/.github/workflows/main.yml#L15-L18).

Maybe the readme could emphasize some of the benefits?

Thanks!

**Comment by svartalf** [comment]
Hi, @dtolnay.

This is a totally legit and great question! You are right to assume that simple `- run:` step is not that different, here is what this Action does differently:

1. It can call `cross` instead of `cargo` binary with [`use-cross: true`](https://github.com/actions-rs/cargo#cross-compilation) flag passed and this allows you to construct such a build matrixes:

```yaml
  compile:
    name: ${{ matrix.toolchain }} / ${{ matrix.triple.target }}
    runs-on: ${{ matrix.triple.os }}
    strategy:
      fail-fast: false
      matrix:
        triple:
          # Tier 1 platforms
          - { os: 'ubuntu-latest',  target: 'x86_64-unknown-linux-gnu', cross: false }
          - { os: 'ubuntu-latest',  target: 'i686-unknown-linux-gnu',   cross: true }
          - { os: 'macOS-latest',   target: 'x86_64-apple-darwin',      cross: false }
          - { os: 'windows-latest', target: 'x86_64-pc-windows-msvc',   cross: false }

          # Tier 2 platforms

          ## ARM64
          - { os: 'ubuntu-latest', target: 'aarch64-unknown-linux-gnu',  cross: true }
          - { os: 'ubuntu-latest', target: 'aarch64-unknown-linux-musl', cross: true }
          ## ARMv7
          - { os: 'ubuntu-latest', target: 'armv7-unknown-linux-gnueabihf',  cross: true }
          - { os: 'ubuntu-latest', target: 'armv7-unknown-linux-musleabihf', cross: true }
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.triple.target }}
          use-cross: ${{ matrix.triple.cross }}
```

2. It enables problem matcher for `cargo` messages. Basically, GitHub automatically runs specific regexp on each line of stdout/stderr and if there is a match, nifty annotation is created for it; in [this execution](https://github.com/actions-rs/example/actions/runs/72008831) you can see that `clippy` execution failed and [in here](https://github.com/actions-rs/example/actions/runs/72008838) a few `rustc` warnings can be found.

This Action was created just after the GitHub Actions became publicly available, and there was no clear vision on how should all that small `actions-rs` ecosystem behave; for example, [`actions-rs/components-nightly`](https://github.com/actions-rs/components-nightly) was deprecated because `rustup` can do that functionality better, and there are plans to deprecate some other Actions too ([`actions-rs/tarpaulin`](https://github.com/actions-rs/tarpaulin) is a first candidate).

So, at this point I'm inclined to agree that plain `- run` step looks much better in a most cases and does almost the same thing. I'll add it to the readme, thanks for pointing it out!
